#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dc26esp
CPPFLAGES += "-I $HOME/opt/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0"

include $(IDF_PATH)/make/project.mk

